language: objective-c

branches:
  only:
    - master

xcode_project: Log.xcodeproj
xcode_scheme: LogTests
osx_image: xcode7.1
xcode_sdk: iphonesimulator9.1

script:
  - xcodebuild test -project Pollock.xcodeproj -scheme PollockTests -destination "platform=iOS Simulator,name=iPhone 6s"
